version: "3.8"

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    networks:
      - frontend

  api:
    build: ./api
    ports:
      - "4000:4000"
    networks:
      - frontend
      - backend

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  frontend:
  backend:

